CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=30
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10
CONFIG_ZMK_BLE_SPLIT_PERIPHERAL_UPDATE_INTERVAL=15

# Prospector status screens (uncomment all to use default)
#CONFIG_PROSPECTOR_STATUS_SCREEN_RADII=y
#CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
#CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
